# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_usercomment_ws_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userwebservice',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userwebservice',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
