# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_auto_20160322_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebservice',
            name='info_score',
            field=models.IntegerField(default=0),
        ),
    ]
