# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxMin',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
            ],
        ),
    ]
