# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxmin',
            name='mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='maxmin',
            name='stdev',
            field=models.FloatField(default=0.0),
        ),
    ]
